### PR TITLE
Stole 2017 readme to be the 2018 readme

### PR DESCRIPTION
**Pull request by ng-david**
i heRd u doughnut likey the master pushies

### CODE REVIEW

**Review by wyapa — COMMENTED** [review]
I'm guessing you tested this?

**Comment by ng-david** [comment]
yeah, the first half

**Comment by srujant** [comment]
banned

**Comment by ng-david** [comment]
hello world

On Jan 30, 2018 12:33 PM, "srujant" <notifications@github.com> wrote:

banned

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bitcamp/bitcamp-app-2018/pull/1#issuecomment-361671136>,
or mute the thread

**Pull request merged**
